#pragma once

// #define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
// #define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U
#define RGB_MATRIX_LED_COUNT 14
#define RGBLIGHT_LED_COUNT 14
#define WS2812_DI_PIN GP21
#define RGB_MATRIX_LED_COUNT RGBLIGHT_LED_COUNT

// #define RGB_MATRIX_SOLID_COLOR 100



