#pragma once


#define WS2812_DI_PIN GP21

#define RGB_MATRIX_LED_COUNT 61
#define RGBLIGHT_LED_COUNT 61

#define ENABLE_RGB_MATRIX_SOLID_SPLASH
#define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
#define ENABLE_RGB_MATRIX_RAINBOW_BEACON